name: Build docker containers and deploy

on:
  push:
    branches: [ master ]
    paths:
      - 'client/**'
      - 'server/**'
      - '.github/workflows/deploy.yml'

jobs:
  push_client:
    name: Push client to Docker Hub
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: client/
          push: true
          tags: bunjdo/bunjgames-client:latest

  push_server:
    name: Push server to Docker Hub
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: server/
          push: true
          tags: bunjdo/bunjgames-server:latest

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [push_client, push_server]
    steps:
      - name: Executing remote command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          PORT: ${{ secrets.SSH_PORT }}
          USERNAME: ${{ secrets.SSH_USERNAME }}
          KEY: ${{ secrets.SSH_KEY }}
          script: |
            cd /srv/bunjgames
            docker stack deploy bunjgames -c ./docker-compose.yaml
            docker image prune -f
